baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "ananke"

[menu]
    [[menu.main]]
        name = "Proyectos"
        url = "/proyectos/"
        weight = 1

    [[menu.main]]
        name = "Portafolio Académico"
        url = "/publicaciones-academico/"
        weight = 2