name : Deploy Hugo site to GitHub Pages
on:
  push:
    branches:
      - main #cuando se haga un push a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositry
        uses: actions/checkout@v4
        with:
          submodules: true # Clona los submódulos del repositorio
          fetch-depth: 0 # Clona todo el historial del repositorio
    
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.145.0' # Instala la versión de Hugo
          #extended: true # Instala la versión extendida de Hugo (necesaria para algunos temas)
          #cache: true # Habilita el caché para acelerar las futuras

      - name: Build site
        run: hugo # Genera el sitio estático de Hugo y lo minimiza

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Token de acceso a GitHub
          publish_dir: ./public # Directorio donde se encuentra el sitio estático generado por Hugo
          publish_branch: gh-pages # Rama donde se publicará el sitio estático
        